In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### **Libraries**

In [ ]:
!pip install pyvi

Collecting pyvi
  Downloading pyvi-0.1.1-py2.py3-none-any.whl (8.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 27.1 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from pyvi) (1.2.2)
Collecting sklearn-crfsuite (from pyvi)
  Downloading sklearn_crfsuite-0.3.6-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pyvi) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pyvi) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pyvi) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pyvi) (3.2.0)
Collecting python-crfsuite>=0.8.3 (from sklearn-crfsuite->pyvi)
  Downloading python_crfsuite-0.9.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (993 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 993.5/993.5 kB 47.3 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from sklearn-crfsuite->pyvi) (1.16.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from sklearn-crfsuite->pyvi) (0.9.0)
Requirement already satisfied: tqdm>=2.0 in /usr/local/lib/python3.10/dist-packages (from sklearn-crfsuite->pyvi) (4.66.1)
ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3108, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 242, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 441, in run
    conflicts = self._determine_conflicts(to_install)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 572, in _determine_conflicts
    return check_install_conflicts(to_install)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/check.py", line 101, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/check.py", line 42, in create_package_set_from_installed
    dependencies = list(dist.iter_dependencies())
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/metadata/pkg_resources.py", line 216, in iter_dependencies
    return self._dist.requires(extras)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2821, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3110, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3120, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3173, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 1131, in parse_string
    loc, tokens = self._parse(instring, 0)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 3886, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 823, in _parseNoCache
    tokens = self.postParse(instring, loc, tokens)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 5420, in postParse
    retToks += ParseResults(
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/results.py", line 150, in __new__
    else list(toklist)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main.py", line 79, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    return run(options, args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 207, in exc_logging_wrapper
    logger.debug("Exception information:", exc_info=True)
  File "/usr/lib/python3.10/logging/__init__.py", line 1465, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/lib/python3.10/logging/handlers.py", line 75, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1218, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/logging.py", line 112, in format
    formatted = super().format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 686, in format
    record.exc_text = self.formatException(record.exc_info)
  File "/usr/lib/python3.10/logging/__init__.py", line 636, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/usr/lib/python3.10/traceback.py", line 119, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "/usr/lib/python3.10/traceback.py", line 502, in __init__
    self.stack = StackSummary.extract(
  File "/usr/lib/python3.10/traceback.py", line 383, in extract
    f.line
  File "/usr/lib/python3.10/traceback.py", line 306, in line
    self._line = linecache.getline(self.filename, self.lineno)
  File "/usr/lib/python3.10/linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python3.10/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python3.10/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "/usr/lib/python3.10/tokenize.py", line 396, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "/usr/lib/python3.10/tokenize.py", line 365, in detect_encoding
    first = read_or_stop()
  File "/usr/lib/python3.10/tokenize.py", line 323, in read_or_stop
    return readline()
KeyboardInterrupt
^C

In [ ]:
import pandas as pd
import numpy as np
from string import digits
from pyvi import ViTokenizer
from keras.layers import *
from gensim.models.keyedvectors import KeyedVectors
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras import regularizers
from keras.callbacks import EarlyStopping
from keras.models import Model
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam
import tensorflow as tf
%matplotlib inline

ModuleNotFoundError: ignored

In [ ]:
from tensorflow.keras.models import load_model

## **Data discovery**

In [ ]:
data_train = pd.read_csv("drive/MyDrive/vlsp_sentiment_train.csv", sep='\t')
data_train.columns =['Class', 'Data']

NameError: ignored

In [ ]:
data_train

NameError: ignored

In [ ]:
print(data_train.shape)

Check null and nan values

In [ ]:
# null values
print(data_train.isnull().sum())

In [ ]:

# no of unique classes
print(np.unique(data_train['Class']))

Get labels and reviews

In [ ]:
labels = data_train.iloc[:, 0].values
reviews = data_train.iloc[:, 1].values

In [ ]:
N_CLASS = 3

## **Data preprocessing**

Remove any digits from the reviews, because there is no way we can handle them

In [ ]:
def process_review(reviews: np.ndarray):
    reviews_processed = []
    for review in reviews:
        review_cool_one = ''.join([char for char in review if char not in digits])
        reviews_processed.append(review_cool_one)

    return reviews_processed

reviews_processed = process_review(reviews)

In [ ]:
def oneHotEncode(labels):
    encoded_labels = []
    for label in labels:
        if label == -1:
            encoded_labels.append([1,0,0])
        elif label == 0:
            encoded_labels.append([0,1,0])
        else:
            encoded_labels.append([0,0,1])

    return np.array(encoded_labels)

encoded_labels = oneHotEncode(labels)

print(encoded_labels.shape)

In [ ]:
# Use PyVi for Vietnamese word tokenizer
def tokenize(reviews_processed: list):
    word_reviews = []
    for review in reviews_processed:
        review = ViTokenizer.tokenize(review.lower())
        word_reviews.append(review.split())

    return word_reviews

word_reviews = tokenize(reviews_processed)

Set up some configurations

In [ ]:
EMBEDDING_DIM = 400 # how big is each word vector
MAX_VOCAB_SIZE = 10000 # how many unique words to use (i.e num rows in embedding vector)
MAX_SEQUENCE_LENGTH = 300 # max number of words in a comment to use

Tokenize

In [ ]:
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE, lower=True, char_level=False)

In [ ]:
tokenizer.fit_on_texts(word_reviews)
sequences_train = tokenizer.texts_to_sequences(word_reviews)
word_index = tokenizer.word_index

In [ ]:
data = pad_sequences(sequences_train, maxlen=MAX_SEQUENCE_LENGTH)
labels = encoded_labels

In [ ]:
print('Shape of X train and X validation tensor:',data.shape)
print('Shape of label train and validation tensor:', labels.shape)

Create embedding matrix

In [ ]:
def create_embedding():
    # load from pre-trained model

    word_vectors = KeyedVectors.load_word2vec_format('drive/MyDrive/vi-model-CBOW.bin', binary=True)
    vocabulary_size = min(len(word_index)+1,MAX_VOCAB_SIZE)
    embedding_matrix = np.zeros((vocabulary_size, EMBEDDING_DIM))
    print("vocab size", vocabulary_size)
    for word, i in word_index.items():
        if i>=MAX_VOCAB_SIZE:
            continue
        try:
            embedding_vector = word_vectors[word]
            embedding_matrix[i] = embedding_vector
        except KeyError:
            embedding_matrix[i]=np.random.normal(0,np.sqrt(0.25),EMBEDDING_DIM)

    del(word_vectors)

    from keras.layers import Embedding
    embedding_layer = Embedding(vocabulary_size,
                                EMBEDDING_DIM,
                                weights=[embedding_matrix],
                                trainable=True)

    return embedding_layer

embedding_layer = create_embedding()

## **Create model**

### **CNN only**

3 layers

In [ ]:
sequence_length = data.shape[1]
filter_sizes = [3,4,5]
num_filters = 100
drop = 0.5

inputs = Input(shape=(sequence_length,))
embedding = embedding_layer(inputs)

################## CNN ONLY ###############################
reshape = Reshape((sequence_length, EMBEDDING_DIM))(embedding)

conv_0 = Conv1D(num_filters, (filter_sizes[0], ), activation='relu', kernel_regularizer=regularizers.l2(0.01))(reshape)

maxpool_0 = MaxPool1D(296)(conv_0)
conv_1 = Conv1D(num_filters, (filter_sizes[1], ), activation='relu', kernel_regularizer=regularizers.l2(0.01))(reshape)

maxpool_1 = MaxPool1D(296)(conv_1)
conv_2 = Conv1D(num_filters, (filter_sizes[2], ), activation='relu', kernel_regularizer=regularizers.l2(0.01))(reshape)

maxpool_2 = MaxPool1D(296)(conv_2)

print(conv_0.shape, conv_1.shape, conv_2.shape)

maxpool_0 = Reshape((-1, num_filters))(maxpool_0)
maxpool_1 = Reshape((-1, num_filters))(maxpool_1)
maxpool_2 = Reshape((-1, num_filters))(maxpool_2)

print(maxpool_0.shape, maxpool_1.shape, maxpool_2.shape)

concat = concatenate([maxpool_0, maxpool_1, maxpool_2])
flatten = Flatten()(concat)

dropout = Dropout(drop)(flatten)
output = Dense(units=3, activation='softmax', kernel_regularizer=regularizers.l2(0.01))(dropout)

cnn_model = Model(inputs, output)

adam = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, weight_decay=0.0)
cnn_model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
cnn_model._name = "CNN"
cnn_model.summary()

Use early stopping with delta < 0.01

In [ ]:
#define callbacks
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.01, patience = 8, verbose=1)
callbacks_list = [early_stopping]

cnn_model.fit(data, labels, validation_split=0.2,
          epochs=20, batch_size=256, callbacks=callbacks_list, shuffle=True)

Plot history

In [ ]:
# Training history
history_dict = cnn_model.history

In [ ]:
# Seperating validation and training accuracy
acc = history_dict.history['accuracy']
val_acc = history_dict.history['val_accuracy']

# Seperating validation and training loss
loss = history_dict.history['loss']
val_loss = history_dict.history['val_loss']

# Plotting
plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.plot(acc)
plt.plot(val_acc)
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(['Accuracy', 'Validation Accuracy'])

plt.subplot(1, 2, 2)
plt.plot(loss)
plt.plot(val_loss)
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend(['Loss', 'Validation Loss'])

plt.show()

In [ ]:
data_test = pd.read_csv("drive/MyDrive/vlsp_sentiment_test.csv", sep='\t')
data_test.columns =['Class', 'Data']

In [ ]:
data_test

In [ ]:
len(data_test)

In [ ]:
labels_test = data_test.iloc[:, 0].values
reviews_test = data_test.iloc[:, 1].values

In [ ]:
encoded_labels_test = oneHotEncode(labels_test)
reviews_processed_test = process_review(reviews_test)
word_reviews_test = tokenize(reviews_processed_test)
sequences_test = tokenizer.texts_to_sequences(word_reviews_test)
data_test = pad_sequences(sequences_test, maxlen=MAX_SEQUENCE_LENGTH)
labels_test = encoded_labels_test

In [ ]:
print('Shape of X test tensor:',data_test.shape)
print('Shape of label test tensor:', labels_test.shape)

In [ ]:
score = cnn_model.evaluate(data_test, labels_test)

In [ ]:
print("%s: %.2f" % (cnn_model.metrics_names[0], score[0]))
print("%s: %.2f%%" % (cnn_model.metrics_names[1], score[1]*100))

In [ ]:
preds = cnn_model.predict(data_test)
pred_labels = np.argmax(preds, axis=1)

In [ ]:
from sklearn.metrics import confusion_matrix

# Assuming labels_test are the true labels
true_labels = np.argmax(labels_test, axis=1)

# Create confusion matrix
cm = confusion_matrix(true_labels, pred_labels)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

# Calculate metrics
accuracy = accuracy_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels, average='macro')
precision = precision_score(true_labels, pred_labels, average='macro')
f_score = f1_score(true_labels, pred_labels, average='macro')

import pandas as pd

# Create a dictionary with your data
result_sum = {
    'Model': 'CNN',
    'Accuracy': [accuracy],
    'Recall': [recall],
    'Precision': [precision],
    'F-Score': [f_score]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(result_sum)

# Display the DataFrame
print(df)

### **LSTM only**

In [ ]:
sequence_length = data.shape[1]
drop = 0.5

inputs = Input(shape=(sequence_length,))
embedding = embedding_layer(inputs)

reshape = Reshape((sequence_length,EMBEDDING_DIM))(embedding)

################## LSTM ONLY ###############################
lstm_0 = Bidirectional(LSTM(1024,))(reshape)

dropout = Dropout(drop)(lstm_0)
output = Dense(units=3, activation='softmax', kernel_regularizer=regularizers.l2(0.01))(dropout)
lstm_model = Model(inputs, output)

adam = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, weight_decay=0.0)
lstm_model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
lstm_model._name = 'LSTM'
lstm_model.summary()

In [ ]:
#define callbacks
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.01, patience=8, verbose=1)
callbacks_list = [early_stopping]

lstm_model.fit(data, labels, validation_split=0.2,
          epochs=20, batch_size=256, callbacks=callbacks_list, shuffle=True)

In [ ]:
# Training history
history_dict = lstm_model.history

In [ ]:
# Seperating validation and training accuracy
acc = history_dict.history['accuracy']
val_acc = history_dict.history['val_accuracy']

# Seperating validation and training loss
loss = history_dict.history['loss']
val_loss = history_dict.history['val_loss']

# Plotting
plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.plot(acc)
plt.plot(val_acc)
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(['Accuracy', 'Validation Accuracy'])

plt.subplot(1, 2, 2)
plt.plot(loss)
plt.plot(val_loss)
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend(['Loss', 'Validation Loss'])

plt.show()

In [ ]:
data_test = pd.read_csv("drive/MyDrive/vlsp_sentiment_test.csv", sep='\t')
data_test.columns =['Class', 'Data']

In [ ]:
labels_test = data_test.iloc[:, 0].values
reviews_test = data_test.iloc[:, 1].values

In [ ]:
encoded_labels_test = oneHotEncode(labels_test)
reviews_processed_test = process_review(reviews_test)
word_reviews_test = tokenize(reviews_processed_test)
sequences_test = tokenizer.texts_to_sequences(word_reviews_test)
data_test = pad_sequences(sequences_test, maxlen=MAX_SEQUENCE_LENGTH)
labels_test = encoded_labels_test

In [ ]:
score = lstm_model.evaluate(data_test, labels_test)

In [ ]:
print("%s: %.2f" % (lstm_model.metrics_names[0], score[0]))
print("%s: %.2f%%" % (lstm_model.metrics_names[1], score[1]*100))

In [ ]:
preds = lstm_model.predict(data_test)
pred_labels = np.argmax(preds, axis=1)

In [ ]:
from sklearn.metrics import confusion_matrix

# Assuming labels_test are the true labels
true_labels = np.argmax(labels_test, axis=1)

# Create confusion matrix
cm = confusion_matrix(true_labels, pred_labels)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

# Calculate metrics
accuracy = accuracy_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels, average='macro')
precision = precision_score(true_labels, pred_labels, average='macro')
f_score = f1_score(true_labels, pred_labels, average='macro')

import pandas as pd

# Create a dictionary with your data
result_summary = {
    'Model': 'LSTM',
    'Accuracy': [accuracy],
    'Recall': [recall],
    'Precision': [precision],
    'F-Score': [f_score]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(result_summary)

# Display the DataFrame
print(df)

### **LSTM + CNN**

In [ ]:
sequence_length = data.shape[1]
filter_sizes = [3,4,5]
num_filters = 100
drop = 0.5

inputs = Input(shape=(sequence_length,))
embedding = embedding_layer(inputs)

################## LSTM ONLY ###############################
reshape = Reshape((sequence_length,EMBEDDING_DIM))(embedding)

################# SINGLE LSTM ####################
# lstm_0 = LSTM(512)(reshape)

# YOU WANNA ADD MORE LSTM LAYERS? UNCOMMENT THIS #
lstm_2 = LSTM(1024, return_sequences=True)(reshape)
lstm_1 = LSTM(512, return_sequences=True)(lstm_2)
lstm_0 = LSTM(256, return_sequences=True)(lstm_1)

############################################################


################## CRNN ####################################
# reshape = Reshape((sequence_length,EMBEDDING_DIM))(embedding)

conv_0 = Conv1D(num_filters, (filter_sizes[0], ),padding="same",activation='relu',kernel_regularizer=regularizers.l2(0.01))(lstm_0)
conv_1 = Conv1D(num_filters, (filter_sizes[1], ),padding="same",activation='relu',kernel_regularizer=regularizers.l2(0.01))(lstm_0)
conv_2 = Conv1D(num_filters, (filter_sizes[2], ),padding="same",activation='relu',kernel_regularizer=regularizers.l2(0.01))(lstm_0)

conv_0 = MaxPool1D(300)(conv_0)
conv_1 = MaxPool1D(300)(conv_1)
conv_2 = MaxPool1D(300)(conv_2)
# Reshape output to match RNN dimension
conv_0 = Reshape((-1, num_filters))(conv_0)
conv_1 = Reshape((-1, num_filters))(conv_1)
conv_2 = Reshape((-1, num_filters))(conv_2)

concat = concatenate([conv_0, conv_1, conv_2])
concat = Flatten()(concat)
# lstm_0 = LSTM(512)(concat)

# YOU WANNA ADD MORE LSTM LAYERS? UNCOMMENT THIS #
# lstm_2 = LSTM(1024, return_sequences=True)(concat)
# lstm_1 = LSTM(512, return_sequences=True)(lstm_2)
# lstm_0 = LSTM(256)(lstm_1)

############################################################

dropout = Dropout(drop)(concat)
output = Dense(units=3, activation='softmax',kernel_regularizer=regularizers.l2(0.01))(dropout)

# this creates a model that includes
lstm_cnn_model = Model(inputs, output)
adam = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, weight_decay=0.0)

lstm_cnn_model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
lstm_cnn_model._name = 'RCNN'
lstm_cnn_model.summary()

In [ ]:
#define callbacks
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.01, patience=8, verbose=1)
callbacks_list = [early_stopping]

lstm_cnn_model.fit(data, labels, validation_split=0.2,
          epochs=20, batch_size=256, callbacks=callbacks_list, shuffle=True)

In [ ]:
# Training history
history_dict = lstm_cnn_model.history

In [ ]:
# Seperating validation and training accuracy
acc = history_dict.history['accuracy']
val_acc = history_dict.history['val_accuracy']

# Seperating validation and training loss
loss = history_dict.history['loss']
val_loss = history_dict.history['val_loss']

# Plotting
plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.plot(acc)
plt.plot(val_acc)
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(['Accuracy', 'Validation Accuracy'])

plt.subplot(1, 2, 2)
plt.plot(loss)
plt.plot(val_loss)
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend(['Loss', 'Validation Loss'])

plt.show()

In [ ]:
data_test = pd.read_csv("drive/MyDrive/vlsp_sentiment_test.csv", sep='\t')
data_test.columns =['Class', 'Data']

In [ ]:
labels_test = data_test.iloc[:, 0].values
reviews_test = data_test.iloc[:, 1].values

In [ ]:
encoded_labels_test = oneHotEncode(labels_test)
reviews_processed_test = process_review(reviews_test)
word_reviews_test = tokenize(reviews_processed_test)
sequences_test = tokenizer.texts_to_sequences(word_reviews_test)
data_test = pad_sequences(sequences_test, maxlen=MAX_SEQUENCE_LENGTH)
labels_test = encoded_labels_test

In [ ]:
score = lstm_cnn_model.evaluate(data_test, labels_test)

In [ ]:
print("%s: %.2f" % (lstm_cnn_model.metrics_names[0], score[0]))
print("%s: %.2f%%" % (lstm_cnn_model.metrics_names[1], score[1]*100))

In [ ]:
preds = lstm_cnn_model.predict(data_test)
pred_labels = np.argmax(preds, axis=1)

In [ ]:
from sklearn.metrics import confusion_matrix

# Assuming labels_test are the true labels
true_labels = np.argmax(labels_test, axis=1)

# Create confusion matrix
cm = confusion_matrix(true_labels, pred_labels)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

# Calculate metrics
accuracy = accuracy_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels, average='macro')
precision = precision_score(true_labels, pred_labels, average='macro')
f_score = f1_score(true_labels, pred_labels, average='macro')

import pandas as pd

# Create a dictionary with your data
result_summary = {
    'Model': 'RCNN',
    'Accuracy': [accuracy],
    'Recall': [recall],
    'Precision': [precision],
    'F-Score': [f_score]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(result_summary)

# Display the DataFrame
print(df)

### **CNN + LSTM**

In [ ]:
sequence_length = data.shape[1]
filter_sizes = [3,4,5]
num_filters = 100
drop = 0.5

inputs = Input(shape=(sequence_length,))
embedding = embedding_layer(inputs)

################## LSTM ONLY ###############################
reshape = Reshape((sequence_length,EMBEDDING_DIM))(embedding)

################# SINGLE LSTM ####################
# lstm_0 = LSTM(512)(reshape)

# YOU WANNA ADD MORE LSTM LAYERS? UNCOMMENT THIS #
# lstm_2 = LSTM(1024, return_sequences=True)(reshape)
# lstm_1 = LSTM(512, return_sequences=True)(lstm_2)
# lstm_0 = LSTM(256, return_sequences=True)(lstm_1)

############################################################


################## CRNN ####################################

conv_0 = Conv1D(num_filters, (filter_sizes[0], ),padding="same",activation='relu',kernel_regularizer=regularizers.l2(0.01))(reshape)
conv_1 = Conv1D(num_filters, (filter_sizes[1], ),padding="same",activation='relu',kernel_regularizer=regularizers.l2(0.01))(reshape)
conv_2 = Conv1D(num_filters, (filter_sizes[2], ),padding="same",activation='relu',kernel_regularizer=regularizers.l2(0.01))(reshape)

conv_0 = MaxPool1D(300)(conv_0)
conv_1 = MaxPool1D(300)(conv_1)
conv_2 = MaxPool1D(300)(conv_2)
# Reshape output to match RNN dimension
conv_0 = Reshape((-1, num_filters))(conv_0)
conv_1 = Reshape((-1, num_filters))(conv_1)
conv_2 = Reshape((-1, num_filters))(conv_2)

concat = concatenate([conv_0, conv_1, conv_2])
# concat = Flatten()(concat)
# lstm_0 = LSTM(512)(concat)

# YOU WANNA ADD MORE LSTM LAYERS? UNCOMMENT THIS #
lstm_2 = LSTM(1024, return_sequences=True)(concat)
lstm_1 = LSTM(512, return_sequences=True)(lstm_2)
lstm_0 = LSTM(256)(lstm_1)

############################################################

dropout = Dropout(drop)(lstm_0)
output = Dense(units=3, activation='softmax',kernel_regularizer=regularizers.l2(0.01))(dropout)

# this creates a model that includes
cnn_lstm_model = Model(inputs, output)
adam = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, weight_decay=0.0)

cnn_lstm_model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
cnn_lstm_model._name = 'CRNN'
cnn_lstm_model.summary()

In [ ]:
#define callbacks
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.01, patience=8, verbose=1)
callbacks_list = [early_stopping]

cnn_lstm_model.fit(data, labels, validation_split=0.2,
          epochs=20, batch_size=256, callbacks=callbacks_list, shuffle=True)

In [ ]:
# Training history
history_dict = cnn_lstm_model.history

In [ ]:
# Seperating validation and training accuracy
acc = history_dict.history['accuracy']
val_acc = history_dict.history['val_accuracy']

# Seperating validation and training loss
loss = history_dict.history['loss']
val_loss = history_dict.history['val_loss']

# Plotting
plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.plot(acc)
plt.plot(val_acc)
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(['Accuracy', 'Validation Accuracy'])

plt.subplot(1, 2, 2)
plt.plot(loss)
plt.plot(val_loss)
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend(['Loss', 'Validation Loss'])

plt.show()

In [ ]:
data_test = pd.read_csv("drive/MyDrive/vlsp_sentiment_test.csv", sep='\t')
data_test.columns =['Class', 'Data']

In [ ]:
labels_test = data_test.iloc[:, 0].values
reviews_test = data_test.iloc[:, 1].values

In [ ]:
encoded_labels_test = oneHotEncode(labels_test)
reviews_processed_test = process_review(reviews_test)
word_reviews_test = tokenize(reviews_processed_test)
sequences_test = tokenizer.texts_to_sequences(word_reviews_test)
data_test = pad_sequences(sequences_test, maxlen=MAX_SEQUENCE_LENGTH)
labels_test = encoded_labels_test

In [ ]:
score = cnn_lstm_model.evaluate(data_test, labels_test)

In [ ]:
print("%s: %.2f" % (cnn_lstm_model.metrics_names[0], score[0]))
print("%s: %.2f%%" % (cnn_lstm_model.metrics_names[1], score[1]*100))

In [ ]:
preds = cnn_lstm_model.predict(data_test)
pred_labels = np.argmax(preds, axis=1)

In [ ]:
from sklearn.metrics import confusion_matrix

# Assuming labels_test are the true labels
true_labels = np.argmax(labels_test, axis=1)

# Create confusion matrix
cm = confusion_matrix(true_labels, pred_labels)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

# Calculate metrics
accuracy = accuracy_score(true_labels, pred_labels)
recall = recall_score(true_labels, pred_labels, average='macro')
precision = precision_score(true_labels, pred_labels, average='macro')
f_score = f1_score(true_labels, pred_labels, average='macro')

import pandas as pd

# Create a dictionary with your data
result_summary = {
    'Model': 'CRNN',
    'Accuracy': [accuracy],
    'Recall': [recall],
    'Precision': [precision],
    'F-Score': [f_score]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(result_summary)

# Display the DataFrame
print(df)

### **K-fold with phoBERT**

In [ ]:
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from gensim.utils import simple_preprocess
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix

import torch.nn as nn
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader

from transformers import get_linear_schedule_with_warmup, AutoTokenizer, AutoModel, logging

import warnings
warnings.filterwarnings("ignore")

logging.set_verbosity_error()

In [ ]:
def seed_everything(seed_value):
    np.random.seed(seed_value)
    torch.manual_seed(seed_value)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed_value)
        torch.cuda.manual_seed_all(seed_value)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = True

seed_everything(86)

In [ ]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
EPOCHS = 6
N_SPLITS = 5


print(device)

In [ ]:
train_df = data_train
test_df = pd.read_csv('drive/MyDrive/vlsp_sentiment_test.csv', sep='\t')

sns.countplot(x='Class', data=train_df)

In [ ]:
train_df = data_train
test_df = pd.read_csv('drive/MyDrive/vlsp_sentiment_test.csv', sep='\t')

train_df['Class'] = train_df['Class'].map({-1:0, 0:1, 1:2})
test_df['Class'] = test_df['Class'].map({-1:0, 0:1, 1:2})

In [ ]:
# We will use Kfold later
# train_df = pd.concat([train_df, valid_df], ignore_index=True)
skf = StratifiedKFold(n_splits=N_SPLITS)
for fold, (_, val_) in enumerate(skf.split(X=train_df, y=train_df.Class)):
    train_df.loc[val_, "kfold"] = fold

In [ ]:
train_df.sample(5)

In [ ]:
train_df.info(), test_df.info()

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base", use_fast=False)

In [ ]:
class SentimentDataset(Dataset):
    def __init__(self, df, tokenizer, max_len=120):
        self.df = df
        self.max_len = max_len
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.df)

    def __getitem__(self, index):
        """
        To customize dataset, inherit from Dataset class and implement
        __len__ & __getitem__
        __getitem__ should return
            data:
                input_ids
                attention_masks
                text
                targets
        """
        row = self.df.iloc[index]
        text, label = self.get_input_data(row)

        # Encode_plus will:
        # (1) split text into token
        # (2) Add the '[CLS]' and '[SEP]' token to the start and end
        # (3) Truncate/Pad sentence to max length
        # (4) Map token to their IDS
        # (5) Create attention mask
        # (6) Return a dictionary of outputs
        encoding = self.tokenizer.encode_plus(
            text,
            truncation=True,
            add_special_tokens=True,
            max_length=self.max_len,
            padding='max_length',
            return_attention_mask=True,
            return_token_type_ids=False,
            return_tensors='pt',
        )

        return {
            'text': text,
            'input_ids': encoding['input_ids'].flatten(),
            'attention_masks': encoding['attention_mask'].flatten(),
            'targets': torch.tensor(label, dtype=torch.long),
        }

    def get_input_data(self, row):
        # Preprocessing: {remove icon, special character, lower}
        text = row['Data']
        text = ' '.join(simple_preprocess(text))
        label = row['Class']

        return text, label

In [ ]:
# Distribution of length of Sentence
all_data = train_df.Data.tolist() + test_df.Data.tolist()
all_data = [' '.join(simple_preprocess(text)) for text in all_data]
encoded_text = [tokenizer.encode(text, add_special_tokens=True) for text in all_data]
token_lens = [len(text) for text in encoded_text]
sns.displot(token_lens)
plt.xlim([0,max(token_lens)])
plt.xlabel('Token Count')

In [ ]:
class SentimentClassifier(nn.Module):
    def __init__(self, n_classes):
        super(SentimentClassifier, self).__init__()
        self.bert = AutoModel.from_pretrained("vinai/phobert-base")
        self.drop = nn.Dropout(p=0.3)
        self.fc = nn.Linear(self.bert.config.hidden_size, n_classes)
        nn.init.normal_(self.fc.weight, std=0.02)
        nn.init.normal_(self.fc.bias, 0)

    def forward(self, input_ids, attention_mask):
        last_hidden_state, output = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask,
            return_dict=False # Dropout will errors if without this
        )

        x = self.drop(output)
        x = self.fc(x)
        return x

In [ ]:
def train(model, criterion, optimizer, train_loader):
    model.train()
    losses = []
    correct = 0

    for data in train_loader:
        input_ids = data['input_ids'].to(device)
        attention_mask = data['attention_masks'].to(device)
        targets = data['targets'].to(device)

        optimizer.zero_grad()
        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        loss = criterion(outputs, targets)
        _, pred = torch.max(outputs, dim=1)

        correct += torch.sum(pred == targets)
        losses.append(loss.item())
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        lr_scheduler.step()

    print(f'Train Accuracy: {correct.double()/len(train_loader.dataset)} Loss: {np.mean(losses)}')

def eval(test_data = False):
    model.eval()
    losses = []
    correct = 0

    with torch.no_grad():
        data_loader = test_loader if test_data else valid_loader
        for data in data_loader:
            input_ids = data['input_ids'].to(device)
            attention_mask = data['attention_masks'].to(device)
            targets = data['targets'].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

            _, pred = torch.max(outputs, dim=1)

            loss = criterion(outputs, targets)
            correct += torch.sum(pred == targets)
            losses.append(loss.item())

    if test_data:
        print(f'Test Accuracy: {correct.double()/len(test_loader.dataset)} Loss: {np.mean(losses)}')
        return correct.double()/len(test_loader.dataset)
    else:
        print(f'Valid Accuracy: {correct.double()/len(valid_loader.dataset)} Loss: {np.mean(losses)}')
        return correct.double()/len(valid_loader.dataset)

In [ ]:
def prepare_loaders(df, fold):
    df_train = df[df.kfold != fold].reset_index(drop=True)
    df_valid = df[df.kfold == fold].reset_index(drop=True)

    train_dataset = SentimentDataset(df_train, tokenizer, max_len=200)
    valid_dataset = SentimentDataset(df_valid, tokenizer, max_len=200)

    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=5)
    valid_loader = DataLoader(valid_dataset, batch_size=32, shuffle=True, num_workers=5)

    return train_loader, valid_loader

In [ ]:
for fold in range(skf.n_splits):
    print(f'-----------Fold: {fold+1} ------------------')
    train_loader, valid_loader = prepare_loaders(train_df, fold=fold)
    model = SentimentClassifier(n_classes=3).to(device)
    criterion = nn.CrossEntropyLoss()
    # Recommendation by BERT: lr: 5e-5, 2e-5, 3e-5
    # Batchsize: 16, 32
    optimizer = AdamW(model.parameters(), lr=2e-5)

    lr_scheduler = get_linear_schedule_with_warmup(
                optimizer,
                num_warmup_steps=0,
                num_training_steps=len(train_loader)*EPOCHS
            )
    best_acc = 0
    for epoch in range(EPOCHS):
        print(f'Epoch {epoch+1}/{EPOCHS}')
        print('-'*30)

        train(model, criterion, optimizer, train_loader)
        val_acc = eval()

        if val_acc > best_acc:
            torch.save(model.state_dict(), f'phobert_fold{fold+1}.pth')
            best_acc = val_acc

**Test**

In [ ]:
def test(data_loader):
    models = []
    for fold in range(skf.n_splits):
        model = SentimentClassifier(n_classes=3)
        model.to(device)
        model.load_state_dict(torch.load(f'phobert_fold{fold+1}.pth'))
        model.eval()
        models.append(model)

    texts = []
    predicts = []
    predict_probs = []
    real_values = []

    for data in data_loader:
        text = data['text']
        input_ids = data['input_ids'].to(device)
        attention_mask = data['attention_masks'].to(device)
        targets = data['targets'].to(device)

        total_outs = []
        for model in models:
            with torch.no_grad():
                outputs = model(
                    input_ids=input_ids,
                    attention_mask=attention_mask
                )
                total_outs.append(outputs)

        total_outs = torch.stack(total_outs)
        _, pred = torch.max(total_outs.mean(0), dim=1)
        texts.extend(text)
        predicts.extend(pred)
        predict_probs.extend(total_outs.mean(0))
        real_values.extend(targets)

    predicts = torch.stack(predicts).cpu()
    predict_probs = torch.stack(predict_probs).cpu()
    real_values = torch.stack(real_values).cpu()
    print(classification_report(real_values, predicts))
    return real_values, predicts

In [ ]:
test_dataset = SentimentDataset(test_df, tokenizer, max_len=50)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True, num_workers=2)
real_values, predicts = test(test_loader)

In [ ]:
class_names = [0,1,2]
sns.heatmap(confusion_matrix(real_values, predicts), annot=True, xticklabels = class_names, yticklabels = class_names)

In [ ]:
def check_wrong(real_values, predicts):
    wrong_arr = []
    wrong_label = []
    for i in range(len(predicts)):
        if predicts[i] != real_values[i]:
            wrong_arr.append(i)
            wrong_label.append(predicts[i])
    return wrong_arr, wrong_label

for i in range(15):
    print('-'*50)
    wrong_arr, wrong_label = check_wrong(real_values, predicts)
    print(test_df.iloc[wrong_arr[i]].Data)
    print(f'Predicted: ({class_names[wrong_label[i]]}) --vs-- Real label: ({class_names[real_values[wrong_arr[i]]]})')

**Inference**

In [ ]:
def infer(text, tokenizer, max_len=120):
    encoded_review = tokenizer.encode_plus(
        text,
        max_length=max_len,
        truncation=True,
        add_special_tokens=True,
        padding='max_length',
        return_attention_mask=True,
        return_token_type_ids=False,
        return_tensors='pt',
    )

    input_ids = encoded_review['input_ids'].to(device)
    attention_mask = encoded_review['attention_mask'].to(device)

    output = model(input_ids, attention_mask)
    _, y_pred = torch.max(output, dim=1)

    print(f'Text: {text}')
    print(f'Sentiment: {class_names[y_pred]}')

### **Roberta LSTM**

In [ ]:
! pip install evaluate
! pip install py_vncorenlp
# ! pip install -U git+https://github.com/huggingface/transformers.git
! pip install -U git+https://github.com/huggingface/accelerate.git

Requirement already satisfied: evaluate in /usr/local/lib/python3.10/dist-packages (0.4.1)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.15.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.23.5)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.66.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.70.15)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2023.6.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.19.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (23.2)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.18.0)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (9.0.0)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (0.6)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.8.6)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (3.13.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2023.7.22)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2023.3.post1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->evaluate) (1.16.0)
Requirement already satisfied: py_vncorenlp in /usr/local/lib/python3.10/dist-packages (0.1.4)
Requirement already satisfied: pyjnius in /usr/local/lib/python3.10/dist-packages (from py_vncorenlp) (1.6.1)
Collecting git+https://github.com/huggingface/accelerate.git
  Cloning https://github.com/huggingface/accelerate.git to /tmp/pip-req-build-djg5ph3x
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/accelerate.git /tmp/pip-req-build-djg5ph3x
  Resolved https://github.com/huggingface/accelerate.git to commit 244122c736141b164242084c659b6dafa4208fea
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0.dev0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0.dev0) (23.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0.dev0) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0.dev0) (6.0.1)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0.dev0) (2.1.0+cu118)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0.dev0) (0.19.4)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0.dev0) (0.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.25.0.dev0) (3.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.25.0.dev0) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.25.0.dev0) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.25.0.dev0) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.25.0.dev0) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.25.0.dev0) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.25.0.dev0) (2.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate==0.25.0.dev0) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate==0.25.0.dev0) (4.66.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate==0.25.0.dev0) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.25.0.dev0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.25.0.dev0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.25.0.dev0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.25.0.dev0) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.10.0->accelerate==0.25.0.dev0) (1.3.0)

In [ ]:
import py_vncorenlp
!mkdir model
py_vncorenlp.download_model(save_dir="model/")

mkdir: cannot create directory ‘model’: File exists
VnCoreNLP model folder model already exists! Please load VnCoreNLP from this folder!

In [ ]:
!mkdir dataset
!mkdir dataset/training
!mkdir output
!mkdir output/checkpoint
!mkdir output/logging

mkdir: cannot create directory ‘dataset’: File exists
mkdir: cannot create directory ‘dataset/training’: File exists
mkdir: cannot create directory ‘output’: File exists
mkdir: cannot create directory ‘output/checkpoint’: File exists
mkdir: cannot create directory ‘output/logging’: File exists

In [ ]:
import os

CURRENT_PATH = os.getcwd()
print(CURRENT_PATH)

/content

In [ ]:
TRAINING_DATASET_PATH = f"{CURRENT_PATH}/dataset/"
OUTPUT_DIR = f"{CURRENT_PATH}/output"
RAW_DATASET_PATH = f"{CURRENT_PATH}/drive/MyDrive/vlsp_sentiment_train.csv"

In [ ]:
import pandas as pd
dataset = pd.read_csv(RAW_DATASET_PATH, sep='\t')

In [ ]:
dataset

      Class                                               Data
0        -1  Mình đã dùng anywhere thế hệ đầu, quả là đầy t...
1        -1  Quan tâm nhất là độ trễ có cao không, dùng thi...
2        -1  dag xài con cùi bắp 98k....pin trâu, mỗi tội đ...
3        -1  logitech chắc hàng phải tiền triệu trở lên dùn...
4        -1  Đang xài con m175 cùi mía , nhà xài nhiều chuộ...
...     ...                                                ...
5095      0  Mình mua máy về đc 1 ngày mà điện thoại khác g...
5096      0  Có bạn nào dùng f1w ko.mình dùng m cảm thấy qu...
5097      0  Dùng oppo mà bộ nhớ 4gb thì k chơi games ...
5098      0  Sao tui thích xài hàng oppo mà lựa toàn mấy đứ...
5099      0  mới mở hộp ,oy mở vào camera mà đã có ảnh chụp...

[5100 rows x 2 columns]

In [ ]:
dataset=dataset.drop_duplicates("Data")
dataset = dataset.dropna()

In [ ]:
import regex as re
import string
import json

In [ ]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'([a-z]+?)\1+',r'\1', text)
    text = re.sub(r"(\w)\s*([" + string.punctuation + "])\s*(\w)", r"\1 \2 \3", text)
    text = re.sub(r"(\w)\s*([" + string.punctuation + "])", r"\1 \2", text)
    # text = re.sub(r"(\d)([^\d.])", r"\1 \2", text)
    # text = re.sub(r"([^\d.])(\d)", r"\1 \2", text)
    text = re.sub(f"([{string.punctuation}])([{string.punctuation}])+",r"\1", text)
    # Remove numbers
    text = re.sub(r"\d", "", text)
    text = text.strip()
    while text.endswith(tuple(string.punctuation+string.whitespace)):
        text = text[:-1]
    while text.startswith(tuple(string.punctuation+string.whitespace)):
        text = text[1:]
    text = re.sub(r"\s+", " ", text)
    return text

def map_label(label):
    label_map = {
        -1: 0,
        0: 1,
        1: 2
    }
    return label_map[label]

In [ ]:
dataset["Data"] = dataset["Data"].map(lambda text: clean_text(text))
dataset["Class"] = dataset["Class"].map(lambda label: map_label(label))

In [ ]:
dataset

      Class                                               Data
0         0  mình đã dùng anywhere thế hệ đầu , quả là đầy ...
1         0  quan tâm nhất là độ trễ có cao không , dùng th...
2         0  dag xài con cùi bắp k .pin trâu , mỗi tội đánh...
3         0  logitech chắc hàng phải tiền triệu trở lên dùn...
4         0  đang xài con m cùi mía , nhà xài nhiều chuột n...
...     ...                                                ...
5095      1  mình mua máy về đc ngày mà điện thoại khác gọi...
5096      1  có bạn nào dùng fw ko . mình dùng m cảm thấy q...
5097      1  dùng opo mà bộ nhớ gb thì k chơi games đc...
5098      1  sao tui thích xài hàng opo mà lựa toàn mấy đứa...
5099      1  mới mở hộp , oy mở vào camera mà đã có ảnh chụ...

[5062 rows x 2 columns]

In [ ]:
dataset["Data"].sample(40)

3468    phê quá dành cho doanh nghiệp với ai cần lưu g...
2065          cấu hình ngon , mua về rồi lên vỏ cũng được
2631                                              đẹp ghê
4836            tr là hàng tq nhái bạn ơi . làm gì rẻ vậy
2500                 đang xài surface pro . quá tuyệt vời
4957    thông báo thiết bị thôi mà , mà lần nào sony c...
3229    từ ngày dùng xiaomi mi tôi rất thích xiaomi bở...
4102    hệ điều hành android ngốn nhiều ram quá , máy ...
4028    mình nghĩ để xem phim cũng khá đã đó . thánh n...
4437    thật ra là giống s edge màn hình to có thêm ch...
1350    từ khi steve jobs chết thì những mẫu iphone về...
2807    có cái này tiện hẳn luôn , thích nhất là nhiệt...
4283    thật ra nhà táo tung sản phẩm của mình ra là đ...
4837    cái ip bạn nói k phải of aple nha . k bgio có ...
2875       thích quá . về vn không biết giá bao nhiêu đây
168                                             thất vọng
2186    công nhận vn chuộng iphone không thua bất cứ n...
1036    y chang mấy cái của xiaomi : v mình chỉ thích ...
4781    sản phẩm này là bằng chứng để có thể đoán được...
88      s edge iron man vẫn đẹp hơn , màu đen như n...
4056    đây là bản test nên rất quan trọng , có thể dẫ...
2263    mình đag dung ip s và cảm thấy chưa cần thiết ...
1278                                         giá chát quá
4515    vậy thì đánh đổi lấy công suất nhỏ hơn hoặc là...
4954    xperia c dual đợt trc nó cũng hứa chắn chắn là...
4148    em nokia chân chính đây ạ . vào chỉ để xem cho...
93               viên pin ít quá . pin . mah thì quá ngon
115                              nhìn như đồ chơi con nít
326     một thất bại của aple ? quả thật nhìn thực tế ...
2690                  không như g chụp rộng mà bị méo nhỉ
4525    bạn mua thì chắc chắn được , còn nghe thì đảm ...
3162       mình có con lumia được năm . dùng vẫn ngon lắm
4193    như vậy thì người dùng có lợi . mà ifan cuồng ...
3696    có bác nào trên tay e đời chưa . ko biết cái d...
690     nói chung thằng em mình mua cái sau ngày trải ...
1136    đeo thiết bị này cẩn thận nhé , vì rất dễ bị d...
3105    tôi xài m từ lúc mới ra tới giờ , ko có lý do ...
4001    ban này nói thế nào vga t chỉ bằng vga trong m...
4234    các bạn ghét samsung cứ chê nhưng về khoản này...
1574    galaxy nào pin cũng nhanh chai và bị nóng máy ...
Name: Data, dtype: object

In [ ]:
dataset=dataset.drop_duplicates("Data")
dataset = dataset.dropna()

In [ ]:
dataset = dataset.drop(dataset[dataset["Data"].map(len) < 2].index)

In [ ]:
import random
_dataset = {
    "train": [],
    "eval": []
}
temp_dataset = [(data["Data"], data["Class"]) for _, data in dataset.iterrows()]
random.seed(1234)
random.shuffle(temp_dataset)

In [ ]:
split_ratio = {
    "train": 0.8,  # 80% of the data for training
    "eval": 0.2    # 20% of the data for evaluation
}

_i = 0
_len = len(temp_dataset)
for mode in split_ratio.keys():
    end = _i + int(_len * split_ratio[mode])
    _dataset[mode] = temp_dataset[_i:end]
    _i = end

In [ ]:
from collections import Counter
import json

for mode in _dataset.keys():
    print(len(_dataset[mode]))
    a = Counter([e[1] for e in _dataset[mode]])
    print(a)
    json.dump({"data":_dataset[mode]}, open(f"{TRAINING_DATASET_PATH}/training/{mode}.json", "w", encoding="utf8"), indent=4, ensure_ascii=False)

4028
Counter({0: 1369, 1: 1341, 2: 1318})
1007
Counter({1: 355, 2: 332, 0: 320})

In [ ]:
!pip install vncorenlp
!pip install onnx
!pip install onnxruntime
!pip install -U git+https://github.com/huggingface/transformers.git
import onnx
from transformers import RobertaForSequenceClassification
from onnxruntime.transformers.optimizer import optimize_model
from transformers.convert_graph_to_onnx import quantize
import onnxruntime as ort
import torch
from functools import reduce

Requirement already satisfied: vncorenlp in /usr/local/lib/python3.10/dist-packages (1.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from vncorenlp) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->vncorenlp) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->vncorenlp) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->vncorenlp) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->vncorenlp) (2023.7.22)
Requirement already satisfied: onnx in /usr/local/lib/python3.10/dist-packages (1.15.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from onnx) (1.23.5)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from onnx) (3.20.3)
Requirement already satisfied: onnxruntime in /usr/local/lib/python3.10/dist-packages (1.16.3)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.10/dist-packages (from onnxruntime) (15.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.10/dist-packages (from onnxruntime) (23.5.26)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.10/dist-packages (from onnxruntime) (1.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from onnxruntime) (23.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from onnxruntime) (3.20.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxruntime) (1.12)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.10/dist-packages (from coloredlogs->onnxruntime) (10.0)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxruntime) (1.3.0)
Collecting git+https://github.com/huggingface/transformers.git
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-m2u1nhze
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-m2u1nhze
  Resolved https://github.com/huggingface/transformers.git to commit f70db28322150dd986298cc1d1be8bc144cc1a88
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (0.19.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0.dev0) (4.66.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.0.dev0) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.0.dev0) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.0.dev0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.0.dev0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.0.dev0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.0.dev0) (2023.7.22)

In [ ]:
from transformers import AutoModel, AutoTokenizer, RobertaForSequenceClassification
from transformers import Trainer, SchedulerType
from transformers.training_args import TrainingArguments, OptimizerNames
from transformers.trainer_utils import IntervalStrategy
import torch
import torch.nn as nn
from torch.utils.data import Dataset
import py_vncorenlp
import json
import random

In [ ]:
from vncorenlp import VnCoreNLP
class PipelineConfig:
    rdrsegmenter = VnCoreNLP("model/VnCoreNLP-1.2.jar", annotators="wseg")

In [ ]:
PipelineConfig.rdrsegmenter.tokenize("Tôi là một kỹ sư AI")

[['Tôi', 'là', 'một', 'kỹ_sư', 'AI']]

In [ ]:
class SentimentConfig:
    def __init__(
            self,
            pretrained_path: str = None,
            dataset_path: str = None,
            training_output_dir: str = None,
            training_learning_rate: float = None,
            training_weight_decay: float = None,
            training_batch_size: int = None,
            training_num_epochs: int = None,
            training_save_total_limit: int = None,
            training_gradient_accumulation_steps: int = None,
            training_eval_steps: int = None,
            training_logging_steps: int = None,
            training_save_steps: int = None,
            training_logging_dir: str = None,
            training_warm_up_ratio: float = None,
            training_device: str = None,
            training_metrics: str = None,
            segmentor_dir:str = None,
            model_input_max_length:int= None,
            model_num_labels:int=None
    ):
        self.pretrained_path = pretrained_path if pretrained_path is not None else "vinai/phobert-base-v2"
        self.dataset_path = dataset_path if dataset_path is not None else f"{TRAINING_DATASET_PATH}/training"
        self.training_output_dir = training_output_dir if training_output_dir is not None else f"{OUTPUT_DIR}/checkpoint/checkpoint20_1"
        self.training_logging_dir = training_logging_dir if training_logging_dir is not None else f"{OUTPUT_DIR}/logging"
        self.training_learning_rate = training_learning_rate if training_learning_rate is not None else 1e-5
        self.training_weight_decay = training_weight_decay if training_weight_decay is not None else 0.01
        self.training_batch_size = training_batch_size if training_batch_size is not None else 16
        self.training_num_epochs = training_num_epochs if training_num_epochs is not None else 10
        self.training_save_total_limit = training_save_total_limit if training_save_total_limit is not None else 10
        self.training_gradient_accumulation_steps = training_gradient_accumulation_steps if training_gradient_accumulation_steps is not None else 2
        self.training_eval_steps = training_eval_steps if training_eval_steps is not None else 50
        self.training_logging_steps = training_logging_steps if training_logging_steps is not None else 50
        self.training_save_steps = training_save_steps if training_save_steps is not None else 50
        self.training_warm_up_ratio = training_warm_up_ratio if training_warm_up_ratio is not None else 0.05
        self.training_device = training_device if training_device is not None else "cuda"
        self.training_metrics = training_metrics if training_metrics is not None else "f1"
        self.model_input_max_length = model_input_max_length if model_input_max_length is not None else 200
        self.model_num_labels = model_num_labels if model_num_labels is not None else 3

In [ ]:
random.seed(2023)

class SentimentDataset(Dataset):
    def __init__(self, config, mode, tokenizer):
        super().__init__()
        self.config = config
        self.tokenizer = tokenizer
        self.data = self.load_dataset(path=f"{self.config.dataset_path}/{mode}.json")
        random.shuffle(self.data)
        print(Counter([e[1] for e in self.data]))
        print(f"Load {len(self.data)} examples for {mode} dataset")

    def load_dataset(self, path: str):
        data = json.load(open(path, "r", encoding="utf8"))
        return data["data"]

    def __getitem__(self, idx):
        data_item = self.data[idx]
        labels = torch.zeros(self.config.model_num_labels)
        labels[data_item[-1]] = 1
        text = data_item[0].lower()
        segmented_text = PipelineConfig.rdrsegmenter.tokenize(text)
        tokenized_text = self.tokenizer([" ".join(segmented_text[0])], padding="max_length", truncation=True, max_length=self.config.model_input_max_length, return_tensors="pt")
        return {
            **tokenized_text,
            "labels": labels
        }

    def __len__(self):
        return len(self.data)

In [ ]:
import os
os.environ["WANDB_DISABLED"] = "true"

In [ ]:
from typing import Optional
from torch.nn import BCEWithLogitsLoss, CrossEntropyLoss, MSELoss
from transformers.modeling_outputs import SequenceClassifierOutput


class SentimentRobertaClassificationHead(nn.Module):
    """Head for sentence-level classification tasks."""

    def __init__(self, config):
        super().__init__()
        self.lstm = nn.LSTM(config.hidden_size, config.hidden_size, 2, bidirectional=True)
        self.dense = nn.Linear(2 * config.hidden_size, config.hidden_size)
        classifier_dropout = (
            config.classifier_dropout if config.classifier_dropout is not None else config.hidden_dropout_prob
        )
        self.dropout = nn.Dropout(classifier_dropout)
        self.out_proj = nn.Linear(config.hidden_size, config.num_labels)

    def forward(self, features, **kwargs):
        # x = features[:, 0, :]  # take <s> token (equiv. to [CLS])
        x = features.mean(dim=1)
        x, (h, c) = self.lstm(x)
        x = self.dropout(x)
        x = self.dense(x)
        x = torch.tanh(x)
        x = self.dropout(x)
        x = self.out_proj(x)
        return x


class SentimentModel(RobertaForSequenceClassification):
  def __init__(self, config):
    super().__init__(config)
    self.classifier = SentimentRobertaClassificationHead(config)

  def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.FloatTensor] = None,
        token_type_ids: Optional[torch.LongTensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        head_mask: Optional[torch.FloatTensor] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        return_dict: Optional[bool] = None,
    ):

      return_dict = return_dict if return_dict is not None else self.config.use_return_dict
      outputs = self.roberta(
          input_ids,
          attention_mask=attention_mask,
          token_type_ids=token_type_ids,
          position_ids=position_ids,
          head_mask=head_mask,
          inputs_embeds=inputs_embeds,
          output_attentions=output_attentions,
          output_hidden_states=output_hidden_states,
          return_dict=return_dict,
      )
      sequence_output = outputs[0]
      logits = self.classifier(sequence_output)

      loss = None
      if labels is not None:
          # move labels to correct device to enable model parallelism
          labels = labels.to(logits.device)
          if self.config.problem_type is None:
              if self.num_labels == 1:
                  self.config.problem_type = "regression"
              elif self.num_labels > 1 and (labels.dtype == torch.long or labels.dtype == torch.int):
                  self.config.problem_type = "single_label_classification"
              else:
                  self.config.problem_type = "multi_label_classification"

          if self.config.problem_type == "regression":
              loss_fct = MSELoss()
              if self.num_labels == 1:
                  loss = loss_fct(logits.squeeze(), labels.squeeze())
              else:
                  loss = loss_fct(logits, labels)
          elif self.config.problem_type == "single_label_classification":
              loss_fct = CrossEntropyLoss()
              loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
          elif self.config.problem_type == "multi_label_classification":
              loss_fct = BCEWithLogitsLoss()
              loss = loss_fct(logits, labels)

      if not return_dict:
          output = (logits,) + outputs[2:]
          return ((loss,) + output) if loss is not None else output

      return SequenceClassifierOutput(
          loss=loss,
          logits=logits,
          hidden_states=outputs.hidden_states,
          attentions=outputs.attentions,
      )

In [ ]:
from evaluate import load
from transformers.trainer_utils import EvalPrediction
from collections import Counter


class SentimentTrainer:
    def __init__(self, config: SentimentConfig = None):
        self.config = config if config is not None else SentimentConfig()
        self.model = SentimentModel.from_pretrained(self.config.pretrained_path, num_labels=self.config.model_num_labels)
        self.model = self.model.float()
        self.model.to(self.config.training_device)
        self.tokenizer = AutoTokenizer.from_pretrained(self.config.pretrained_path)
        self.metrics = {
            "precision": load("precision"),
            "recall": load("recall"),
            "f1": load("f1"),
            "accuracy": load("accuracy")
        }
        self.train_dataset, self.eval_dataset = self.load_dataset()

        self.init_trainer()

    def load_dataset(self):
        train_dataset = SentimentDataset(config=self.config, mode="train", tokenizer=self.tokenizer)
        eval_dataset = SentimentDataset(config=self.config, mode="eval", tokenizer=self.tokenizer)
        return train_dataset, eval_dataset

    def collator(self, data):
        batch = {}
        _keys = data[0].keys()
        for key in _keys:
            batch[key] = torch.vstack([ele[key] for ele in data]).to(self.config.training_device)

        return batch

    def compute_metrics(self, eval_predictions: EvalPrediction):
        predictions, labels = eval_predictions
        predictions = torch.from_numpy(predictions).softmax(dim=-1).argmax(dim=-1)
        labels = torch.from_numpy(labels).argmax(dim=-1)

        output =  {
            "precision": self.metrics["precision"].compute(predictions=predictions, references=labels,
                                                           average="weighted")["precision"],
            "recall": self.metrics["recall"].compute(predictions=predictions, references=labels, average="weighted")["recall"],
            "f1": self.metrics["f1"].compute(predictions=predictions, references=labels, average="weighted")["f1"],
            "accuracy": self.metrics["accuracy"].compute(predictions=predictions, references=labels)["accuracy"]
        }
        return output

    def init_trainer(self):
        training_args = TrainingArguments(
            output_dir=self.config.training_output_dir,
            evaluation_strategy=IntervalStrategy.STEPS,
            save_strategy=IntervalStrategy.STEPS,
            per_device_train_batch_size=self.config.training_batch_size,
            per_device_eval_batch_size=self.config.training_batch_size,
            learning_rate=self.config.training_learning_rate,
            weight_decay=self.config.training_weight_decay,
            save_total_limit=self.config.training_save_total_limit,
            num_train_epochs=self.config.training_num_epochs,
            gradient_accumulation_steps=2,
            eval_steps=self.config.training_eval_steps,
            fp16=self.config.training_device == "cuda",
            push_to_hub=False,
            dataloader_num_workers=0,
            logging_dir=self.config.training_logging_dir,
            logging_strategy=IntervalStrategy.STEPS,
            logging_steps=self.config.training_logging_steps,
            save_steps=self.config.training_save_steps,
            logging_first_step=False,
            optim=OptimizerNames.ADAMW_TORCH,
            load_best_model_at_end=True,
            metric_for_best_model=self.config.training_metrics,
            warmup_ratio=self.config.training_warm_up_ratio,
            lr_scheduler_type=SchedulerType.COSINE_WITH_RESTARTS,
            dataloader_pin_memory=False
        )
        self.trainer = Trainer(
            model=self.model,
            args=training_args,
            train_dataset=self.train_dataset,
            eval_dataset=self.eval_dataset,
            tokenizer=self.tokenizer,
            data_collator=self.collator,
            compute_metrics=self.compute_metrics
        )

    def train(self):
        self.trainer.train()

    def eval(self):
        print(self.trainer.evaluate(eval_dataset=self.eval_dataset))

In [ ]:
trainer = SentimentTrainer()

Some weights of SentimentModel were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['classifier.lstm.bias_hh_l1_reverse', 'classifier.out_proj.bias', 'classifier.lstm.bias_ih_l0', 'classifier.lstm.weight_ih_l0_reverse', 'classifier.lstm.weight_hh_l0_reverse', 'classifier.lstm.weight_ih_l1_reverse', 'classifier.lstm.bias_hh_l1', 'classifier.lstm.weight_hh_l1', 'classifier.lstm.weight_ih_l1', 'classifier.lstm.bias_ih_l1', 'classifier.lstm.bias_hh_l0', 'classifier.lstm.weight_hh_l1_reverse', 'classifier.lstm.weight_ih_l0', 'classifier.lstm.bias_ih_l0_reverse', 'classifier.lstm.bias_hh_l0_reverse', 'classifier.lstm.weight_hh_l0', 'classifier.dense.bias', 'classifier.lstm.bias_ih_l1_reverse', 'classifier.out_proj.weight', 'classifier.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Counter({0: 1369, 1: 1341, 2: 1318})
Load 4028 examples for train dataset
Counter({1: 355, 2: 332, 0: 320})
Load 1007 examples for eval dataset

In [ ]:
trainer.train()

Removed shared tensor {'classifier.lstm.weight_hh_l0_reverse', 'classifier.lstm.weight_ih_l1_reverse', 'classifier.lstm.bias_hh_l0_reverse', 'classifier.lstm.weight_hh_l0', 'classifier.lstm.bias_hh_l1_reverse', 'classifier.lstm.bias_hh_l1', 'classifier.lstm.weight_hh_l1', 'classifier.lstm.weight_ih_l1', 'classifier.lstm.bias_ih_l1', 'classifier.lstm.bias_ih_l1_reverse', 'classifier.lstm.weight_ih_l0_reverse', 'classifier.lstm.bias_hh_l0', 'classifier.lstm.weight_hh_l1_reverse', 'classifier.lstm.bias_ih_l0', 'classifier.lstm.bias_ih_l0_reverse'} while saving. This should be OK, but check by verifying that you don't receive any warning while reloading
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
There were missing keys in the checkpoint model loaded: ['classifier.lstm.weight_hh_l0', 'classifier.lstm.bias_ih_l0', 'classifier.lstm.bias_hh_l0', 'classifier.lstm.weight_ih_l0_reverse', 'classifier.lstm.weight_hh_l0_reverse', 'classifier.lstm.bias_ih_l0_reverse', 'classifier.lstm.bias_hh_l0_reverse', 'classifier.lstm.weight_ih_l1', 'classifier.lstm.weight_hh_l1', 'classifier.lstm.bias_ih_l1', 'classifier.lstm.bias_hh_l1', 'classifier.lstm.weight_ih_l1_reverse', 'classifier.lstm.weight_hh_l1_reverse', 'classifier.lstm.bias_ih_l1_reverse', 'classifier.lstm.bias_hh_l1_reverse'].

In [ ]:
best_checkpoint_path = f"{trainer.config.training_output_dir}/checkpoint-1250"
best_model = RobertaForSequenceClassification.from_pretrained(best_checkpoint_path, ignore_mismatched_sizes=True)
best_model.eval()
tokenizer = AutoTokenizer.from_pretrained(best_checkpoint_path)

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at /content/output/checkpoint/checkpoint20_1/checkpoint-1250 and are newly initialized because the shapes did not match:
- classifier.dense.weight: found shape torch.Size([768, 1536]) in the checkpoint and torch.Size([768, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Test**

In [ ]:
import scipy

In [ ]:
TEST_PATH = f"drive/MyDrive/vlsp_sentiment_test.csv"
test_dataset = pd.read_csv(TEST_PATH, sep='\t')

In [ ]:
test_dataset

      Class                                               Data
0        -1  Nói thiệt là mình thì thì chuột nào mình cũng ...
1        -1  Đang dùng mx1. Cũng ngon nhưng chưa đầy năm mà...
2        -1  Chưa thấy đc điểm thuyết phục để mua, nhất là ...
3        -1  Những phần xem báo tra cứu bản đồ, dịch vụ.. d...
4        -1  ĐÚNG LÀ MUA Ở VIỆT NAM KHÔNG ỨNG DỤNG ĐƯỢC GÌ ...
...     ...                                                ...
1045      0                                         30 củ à :)
1046      0  Apple bán dc thi samsung cũng lời nhiêu. Ng...
1047      0  có thể giúp android vượt trội so với ios chớ c...
1048      0  Mẹ mình từng sang Đài Loan và có mua 1 cái iph...
1049      0  Tùng Minh Nguyễn điện thoại của vk bị như này ...

[1050 rows x 2 columns]

In [ ]:
# Define a mapping dictionary
class_mapping = {-1: 0, 0: 1, 1: 2}

# Apply the mapping to the 'Class' column
test_dataset['Class'] = test_dataset['Class'].map(class_mapping)

In [ ]:
test_dataset

      Class                                               Data
0         0  Nói thiệt là mình thì thì chuột nào mình cũng ...
1         0  Đang dùng mx1. Cũng ngon nhưng chưa đầy năm mà...
2         0  Chưa thấy đc điểm thuyết phục để mua, nhất là ...
3         0  Những phần xem báo tra cứu bản đồ, dịch vụ.. d...
4         0  ĐÚNG LÀ MUA Ở VIỆT NAM KHÔNG ỨNG DỤNG ĐƯỢC GÌ ...
...     ...                                                ...
1045      1                                         30 củ à :)
1046      1  Apple bán dc thi samsung cũng lời nhiêu. Ng...
1047      1  có thể giúp android vượt trội so với ios chớ c...
1048      1  Mẹ mình từng sang Đài Loan và có mua 1 cái iph...
1049      1  Tùng Minh Nguyễn điện thoại của vk bị như này ...

[1050 rows x 2 columns]

In [ ]:
temp_dataset = [(data["Data"], data["Class"]) for _, data in test_dataset.iterrows()]

In [ ]:
_dataset = {
    "test" : []
}

split_ratio = {
    "test": 1
}

In [ ]:
_i = 0
_len = len(temp_dataset)
_dataset["test"] = temp_dataset[_i:int(_len*split_ratio["test"])+1]

In [ ]:
CURRENT_PATH

'/content'

In [ ]:
!mkdir dataset/testing
print(len(_dataset["test"]))
a = Counter([e[1] for e in _dataset["test"]])
print(a)
json.dump({"data":_dataset["test"]}, open(f"{CURRENT_PATH}/dataset/testing/test.json", "w", encoding="utf8"), indent=4, ensure_ascii=False)

mkdir: cannot create directory ‘dataset/testing’: File exists
1050
Counter({0: 350, 2: 350, 1: 350})

In [ ]:
def reverse_label(label):
    label_map = {
        0: "NEG",
        1: "NEU",
        2: "POS"
    }
    return label_map[label]

In [ ]:
import json
test_dataset_json = json.load(open(f"{CURRENT_PATH}/dataset/testing/test.json", "r", encoding="utf8"))

In [ ]:
_len = len(_dataset["test"])
subset = random.choices(test_dataset_json["data"], k=_len)
acc=0
for example, label in subset:
    segmented_text = [" ".join(PipelineConfig.rdrsegmenter.annotate(example))]
    _inputs = tokenizer(segmented_text, return_tensors="pt", padding=True)

    # Feed the inputs to the model
    model_output = best_model(**_inputs)

    # Detach the tensor and convert it to numpy
    logits = model_output.logits.detach().numpy()

    # Get the probabilities by applying softmax
    probabilities = scipy.special.softmax(logits, axis=-1)

    # Get the predicted label
    pred = probabilities.argmax(-1).tolist()[0]

    if label == pred:
        acc += 1
    else:
        print("==============")
        print(example)
        print(reverse_label(label), "!=", reverse_label(pred))

# Calculate accuracy
accuracy = acc / _len
print(f"Accuracy: {accuracy}")

==============
8gb là đủ rồi, còn card thì lấy asus 4gb 4m hoặc gtx950 4m tuỳ sở thích
NEU != POS
==============
note 7 5.7 icnch ma be hon nhieu so voi iphone 6s plus co man 5.5 inch nhi. Co ve apple thiet ke iphone man to ko can doi
NEU != POS
==============
Hàng chính hãng giá khoảng từ 16 triệu. Hàng của bạn định mua là hàng 10 hãng giá từ khoảng 500 tệ. Bạn có thể mua xài để có chút kinh nghiệm và không bị lầm lần sau. Chúc bạn tìm được điện thoại như ý !
NEU != POS
==============
Nút home cảm ứng ở trong màn hình sẽ là một thất bại tiếp theo của Sony
NEG != POS
==============
Mua về vài năm nó hỏng thì chát nhỉ. Mà các bác cho e hỏi. Mua ssd về chỉ nghi vào thôi k sóa đi thì để lâu có hỏng k nhỉ.
NEU != POS
==============
hang nao ma cha la hang chinh hang . hong le mang tu my zia la hang khong chinh hang a may thanh
NEU != POS
==============
Apple không nên chạy theo mẫu HTC, quá xấu. Cứ để thiết kế theo kết cấu phom như 6s Plus và 5s và 5SE là ok nhất.
NEG != POS
==============
Đã từng dùng con Neo7, ram gì có 1GB, dùng gì mà chán kinh. tưởng đâu đt giá rẻ bị vậy, bữa cầm con Zenfone Laser của thằng bạn lên so thì thấy màn hình đt mình nó tệ kinh khủng, sài còn mướt hơn nữa chứ. mình phải bán gấp con neo7 đó đi
NEG != POS
==============
Căn bản là ko ăn thua vì hệ điều hành adroi quá rẽ bẻ khóa...
NEG != POS
==============
Mình đã nâng cấp và đã lãnh hậu quả: Màn hình bị rung khiến chữ và hình ảnh bị nhoè. Đã restore các kiểu vẫn không khắc phục được
NEG != POS
==============
quá xấu, không có gì đột phá cho siêu phẩm S7, thất vọng
NEG != POS
==============
Đua làm gì ngta thường dùng iphone hoặc samssung thôi
NEU != POS
==============
Sao nó xấu đau xấu đớn vậy trời
NEG != POS
==============
Đọc bài viết của chủ Topic xin mạo muội bình loạn vài câu: 1. Chủ topic khá am tường về công nghe, mặc dù hình như là dân business. 1. AW thực sự hữu ích cho dân Business chứ không phải cho dân yêu công nghệ ( Vd coder ngồi 1 chỗ tự kỷ thì có thể dùng IP, hạn chế dùng aw chữ nhỏ hại mắt vì coder dán mắt vào màn hình cả ngày rồi ) và càng không phải dành cho thời trang. Các fan cồng của Apple nếu mua AW nên đọc bài này để cân nhắc, ko nên phí tiền vô ích nếu bạn ko phải là business man/ hoặc ko đang sống ở các nước phát triển về công nghệ (vd ở VN thì đeo aw ko biết để làm gì ). 3. Các bạn sử dụng aw cẩn thận, ko chừng cận thị, vì aw khá bé mà hiển thị khá nhiều thông tin => chữ bé, đọc nhiều lồi mắt. Dù sao cũng thanks chủ Topic đã chia sẻ kinh nghiệm, hy vòng 3-5 năm tới ở VN mình có thể xài AW.
NEU != POS
==============
Xấu nhưng vẫn mua vì hệ điều hành iOS thật tuyệt vời.
NEU != POS
==============
960 gọi bằng cụ nhé, 960 thua tầm 60%
NEU != POS
==============
Hơn 1 năm rùi có thấy đâu, muh nghe nói bản 2 chỉ thêm cảm biến nhịp tim, ko có giao diện hiển thị
NEU != POS
==============
Giá này làm bằng vàng có khi vẫn rẻ hơn.
NEG != POS
==============
Nhìn cũng được nhưng nhỡ nó rơi cái thì toi
NEG != POS
==============
Quả này chết chắc rồi BB ơi. Quá thất vọng về thiết kế của BB phiên bản này!
NEG != POS
==============
Nói nhanh cho vuông là cạn ý tưởng .
NEG != POS
==============
Với 7tr thì mua được con Mini 2. Làm sao công suất đọ lại được với cả con Samsung này, chưa kể chất âm cũng không đọ được. Vậy tại sao cứ phải mua bose, trong khi với giá tiền này, nhu cầu phổ thông là con J850 này đáp ứng dư rồi.
NEU != POS
==============
IPhone SE tạm dịch là "Y Phôn Sẽ Ế" ạ. Em dịch vậy có đúng không mấy huynh?
NEG != POS
==============
để so sánh camera thì hơi khó bác ạ.mỗi dòng camera của mỗi hãng có những ưu điểm khác nhau.riêng như trên camera của dòng Sharp này, camera chỉ 13,1 MP nhưng hình ảnh chụp thì rất sống động, màu sắc cũng đẹp, được trang bị khẩu độ 1,9 bright eye. Thêm nữa ở camera của SH-04F lần này được trong bị thêm công nghệ Night catch 2 cho cảm nhận chụp ảnh đêm rất tuyệt. còn thì bác có thể cảm nhận thêm để xem 2 camera nó khác nhau thế nào
NEU != POS
==============
hết hứng với bb :(( 5 năm trung thành giờ phải kết thúc :((
NEG != POS
==============
mua Táo đi , Sony sài dở , nếu bạn đam mê game thì sẽ thấy chất lượng của Sony kém thế nào . Nếu chỉ dùng để chụp hình thì đẹp nhưng quay phim thì rất nóng .
NEG != POS
==============
Bán ra vào 10h ngày 7/6 nhé, giá là 149 nhân dân tệ khoảng 500k vnd
NEU != POS
==============
Mua một mớ về cất sau này làm đồ cổ...kkk
NEU != POS
==============
Máy xấu thật!...
NEG != POS
==============
Thiết kế bo tròn và kiểu dáng ko thay đổi qua nhiều phiên bản, giờ nhìn iPhone càng ngày càng thấy quê quê.
NEG != POS
==============
phải mua con mới được, thấy anh em hưởng ứng quá mà lazada nó cũng đang giảm giá nên mua không nhỉ?
NEU != POS
==============
Biết đâu S8 thiết kế đẹp hơn iP7 thì sao?
NEU != POS
==============
Có, bình thường nhé. Mình không hiểu rõ nguyên lí nhưng nó vẫn rung báo đều hàng ngày. Hôm kia buổi sáng mình đang cập nhật ios 9 mà nó vẫn rung đó thôi
NEU != POS
==============
Theo mình biết Sony bảo hành 24 Tháng , như bạn nói tv của bạn đã hết bảo hành =  hơn 2 năm. Mà công nghệ 4K tên tivi Sony đặc biệt là dòng 43 inches chỉ xuất hiện ở thị trường VN vào khoảng giữa 2015... Có dấu hỏi nhẹ chỗ này ⁉⁉
NEU != POS
==============
Trả khác con Oakley của em. Trông còn đẹp hơn
NEG != POS
==============
Chưa ấn tượng lắm
NEG != POS
==============
Vết xe đỗ của motorola và bb đã cán lên !!!!!!!!
NEG != POS
==============
Mình chưa từng yêu em Smart nào như dòng Note. Nhưng kẹt nỗi ít tiền.
NEU != POS
==============
Bạn đọc kĩ lại bài nhé, Celeron là dòng chip cùi nhất của Intel , chơi LoL lowest settings còn chưa chắc được
NEU != POS
==============
đó cũng là một sự cố gắng đó rồi bạn. Tạo một hệ điều hành mới rất khó về vốn và con người. Chỉ có các tập đoàn lớn mới có thể làm được thôi
NEU != POS
==============
Mình chưa từng yêu em Smart nào như dòng Note. Nhưng kẹt nỗi ít tiền.
NEU != POS
==============
Ở VN người làm giám đốc chi cho đt là 0 đồng ( vì cơ quan cấp IPHONE cho) công nhân chi 20triệu trở lên mua IPHONE vì phải tự sắm. Ra đường giám đốc và công nhân đẳng cấp ngang nhau. Về nhà giám đốc ở biệt thự hay căn hộ cao cấp vì thu nhập to lại không lo sắm IPHONE. Công nhân vì nghèo sỉ diện nên ráng sắm IPHONE cho bằng anh bằng em ở nhà thuê dột nát vì lương ít lại còn phải chi tiền mua đt. Kết quả người lại càng giàu lại càng giàu thêm vì làm lương to mà chả phải mua sắm gì - mọi thứ đã có công ty lo và cả nhân viên sắm cho để lấy lòng sếp - người nghèo lại càng nghèo thêm vì đi làm chả công ty nào cấp bất cứ thứ gì thậm chí không có bảo hiểm - thứ tối thiểu mà người lao động đáng ra phải được hưởng và cả cái khoản bôi trơn quà biếu xén cho sếp mỗi khi lễ tết đến nữa chứ. Tết tết đến rồi kẻ cười người khóc
NEU != POS
==============
Hi h van còn giữ em V3 T-Mobile , hy vọng cũng dc sang chanh ké với ng ta !
NEU != POS
==============
Chả có gì thay đổi vượt bậc về ngoại hình. Hy vọng không giống như lời đồn..
NEG != POS
==============
Hi hi..bên Mỹ Iphone rẻ lắm bác ạ..tui xài nhà mạng bản QT mún đổi dt mới nào chỉ cần bù thêm ít tiền thôi.. lần về Vn trước bị giật mất con 6s plus nên giờ hãi lắm
NEU != POS
==============
giống các máy android bình thường mà bác ^^! hy vọng có người làm sr bác em chưa chụp đc! nhưng cột sóng căng tràn khi bật 3G ạ từ lúc sử dụng e chưa thấy hiện tượng mất sóng hay gì hết T.T
NEU != POS
==============
Dùng vân tay là đơn giản và hữu hiệu nhất rồi,còn bày trò làm gì.
NEG != POS
==============
bị giật mát thôi. con ip6 t xài cũng bị thế. câu lại đường dây mát từ vỏ máy tính vô cây đinh đóng vào góc tường là hết bị ngay thôi.
NEG != POS
==============
Cũng mới xài aw được 3 ngày, nhìn chung nếu ở vn thì chưa thực sự hữu ích với số tiền bỏ ra trừ khi bạn là người chơi thể thao hằng ngày tận dụng tốt được chức năng activity. Aw tiện lợi khi xem lịch, thời tiết, note, nhận được thông báo nhanh từ email, fb, message mà không cần móc điện thoại trong túi ra. Màn hình hiển thị rất đẹp, cảm ứng nhạy. Mình thì quen nghe gọi bằng điện thoại nên chức năng nghe gọi thẳng từ aw cũng thử cho vui, có lẽ là chưa quen. Pin của aw cũng không yếu sinh lý như mình tưởng, sau 1 ngày vooc đủ thứ đến tối vẫn còn hơn 20%. Có chế độ tiết kiệm pin nếu bạn không có điều kiện sạc ngày một. Tuy nhiên 1 con watch cho dù 2 ngày sạc pin 1 lần cũng hơi bất tiện, có thể aw2,3 sẽ cải thiện được. Đeo khá đẹp, không thấy quá dày. Còn chức năng phải voọc thêm đã, có lẽ apple sẽ cập nhật liên tục các bản update cho aw vì mình thấy apple vẫn chưa tận dụng hết tính năng phần cứng của aw.
NEU != POS
==============
Quá đắt. Giá này có thể mua được FF A7 cũng của Sony, còn crop thì là Fujji XT1 quá ngon lành.
NEG != POS
==============
phạm vi của bluetooth rất ngắn chưa kể nếu che chắn quá kĩ như cốp xe là nghe tiếng được tiếng mất trừ khi bác luôn kè kè cái đt bên mình thì chất lượng cuộc gọi mới tốt được, đó là chưa kể đến nếu dùng đt cũ hoặc sw của tàu thì bluetooth chỉ ở v3 hạn hữu có cả v2 thì chất lượng cuộc gọi còn tệ nữa, còn nếu ngoài phạm vi bt thì nó lại là vấn đề của 1 cái sim khác nói chung thì dù cho sw có sim hay không sim gì thì bác vẫn kè kè cái smp bên người thôi
NEG != POS
==============
Phần mềm androi 6.0.1 trên s6 nếu đặt chế đọ tiết kiệm pin gần như tất cả kết nối internet sẽ ngừng khi màn hình tắt .
NEU != POS
==============
Sao bằng bản s7 batman đươc.
NEG != POS
==============
" Của rẻ là của ôi " , biết đâu đây là một cú lừa ngoạn mục nữa ?
NEG != POS
==============
Không thấy chỗ nào bán với giá tầm 700 nhỉ, toàn thấy 990-1200k,chát quá
NEU != POS
==============
Giá này làm bằng vàng có khi vẫn rẻ hơn.
NEG != POS
==============
Có, bình thường nhé. Mình không hiểu rõ nguyên lí nhưng nó vẫn rung báo đều hàng ngày. Hôm kia buổi sáng mình đang cập nhật ios 9 mà nó vẫn rung đó thôi
NEU != POS
==============
chuẩn bác, hùi đầu thiếu tiền nên chỉ mua r7 240 thay vì 750ti, chơi game mình thích gtav fifa16 sợ lag tung chảo ai dè vẫn chạy ngon 30fps bởi nên có thêm time để dành cho nâng cấp lên 480 hay 1070
NEU != POS
==============
Chức năng cũa iphone thì ko có gì đặt biệt dể nhàm chán
NEG != POS
==============
16900000 đắt vãi
NEG != POS
==============
Dang sai ipad pro la da thay lon lam roi con ss nay lam ra chac de nhin choi thoi ai ma mua vi su qua kho cua no
NEG != POS
==============
Logitech là ok rồi, nhừng mình thấy giá chát quá - đang xài M545 thấy ok.
NEU != POS
==============
máy này nên gọi là kêu ca :))). xem xong đến giá thấy ai cũng la :D
NEG != POS
==============
con này thiết kế xấu kinh điển .nhung ko rẻ đâu
NEG != POS
==============
Nhưng gear fit của ss chỉ tương thích với điện thoại ss -_- chứ không cũng đã mua rồi
NEU != POS
==============
Cảm biến vân tay iPhone giờ chậm hơn cả Huawei, Meizu, ai định nghĩa lại ai? Vân tay chắc chắn sẽ hết thời, quá nhiều nhược điểm, cực thiếu an toàn
NEG != POS
==============
xấu dzã man (rợ)
NEG != POS
==============
Sóng bluetooth thì vẫn luôn kém ổn định so với sóng receiver.
NEU != POS
==============
Xai chuot so nhat bi double click.
NEU != POS
==============
Em đã sửa Đc Lỗi ko gửi đc Mà E Thấy con Này Chụp Ảnh ko đc đẹp như Mây con 8 chấm khác Nhỉ Mà bi Kiểu khi Chưa chụp thì Nhin Khá Nét Nhưng Chụp xong thi Ảnh lại Ko Đẹp Lắm có nhiều Tấm bị mờ
NEG != POS
==============
Sao trông dầy thế nhỉ
NEG != POS
==============
Màn hình tối và mờ thì ông lại chống chế là bảo vệ mắt. Giúp cho mắt được đeo kính cận sớm
NEG != POS
==============
Nút nguồn thiết kế dở quá, bấm chờ 4 - 5 giây mới tắt hoặc mở nguồn. Nhiều khi gây ức chế. Rất không tiện dụng khoản này.
NEG != POS
==============
Sao kỳ vậy ?! Máy có chống nước mà không cho chụp ảnh dưới nước rồi từ chối bảo hành. Chán SONY...
NEG != POS
==============
Hết ý tưởng trong thiết kế cũng như trong ứng dụng khác biệt. Ngoài cái thiết kế to thô kệch, chấm thêm vào camera vài chấm. ngoài ra chẳng có gì khác. chán
NEG != POS
==============
Thật xấu...
NEG != POS
==============
Sao trông dầy thế nhỉ
NEG != POS
==============
Mình vừa làm 1 e của lazada nhập mả giảm giá vô giảm thêm 100k còn 748k , nhưng nó báo hàng bảo hành bằng hóa đơn 3 tháng và kg bảo hành là quái j vậy các bác thông tin thanh toán nó báo vậy . bác nào rành cho mình bt với , tại sao báo "bảo hành bằng hóa đơn 3 tháng kg bảo hành" mâu thuẩn quá bác nào mua của lazada rồi cho mình bt với vậy có bảo hành kg các bác thông tin đơn hàng gửi 1ua mail nó báo mình vậy đấy
NEU != POS
==============
Dòng máy dell lỗi phần cứng kinh khủng, máy chạy hay bị lắc, pin thì bị lỗi không sạc....
NEG != POS
==============
các bác cho em hỏi, em reply trên SMS trên Apple oắt, mình nói tiếng việt mà nó cứ nhận sang tiếng anh thì phải làm sao ạ, trên iphone thì nhận tiếng việt rất tốt
NEU != POS
==============
Chưa so về cấu hình, hãy so về phần cứng và còn sử dụng hay không. IP4/S1 4s/S2 5/S3 5S/S4 và Hiện giờ bao nhiêu người còn sài con S1 và IP4 4S thì vẫn đang sài phổ thông, S2 thì vắng bóng tạm thời. 5 Thì vẫn bán đầy thị trường, S3 thì mất tích. Chỉ nhiêu đó thui đã đủ biết sản phẩm nào hơn rùi.
NEU != POS
==============
Bác cho e hỏi con x7 gps định vị èo quá có cách nào khắc phục ko
NEU != POS
==============
Nếu đúng như vậy thì Apple đóng cửa mà nằm ăn táo nhá. Quá xấu!
NEG != POS
==============
Cug y kien va Minh da co mau den xam.
NEU != POS
==============
Cứ thế này thì apple đuối trước binh đoàn android thôi.Cần có cuộc cách mạng về thiêt kế chứ ko thể hi cọng mãi vào IOS được.
NEG != POS
==============
Quá bình thường so với giá trị của nó, Tính ra SS6 vẫn đep hơn.
NEG != POS
==============
Đây là dòng sản phẩm thông thường đó bạn, dĩ nhiên là không thể so với những dòng nghe chuyên nghiệp giá mấy chục triệu. Nhưng nhu cầu tầm trung vậy là quá ổn rồi.
NEU != POS
==============
Khá nhiều hãnh ra màu này rồi bạn kể cả những hãng sản xuất máy nghe nhạc. Bạn thử tìm hiểu ak 240 blue note đi bạn sẽ định nghĩa lại khái niệm đẹp và sáng tạo
NEU != POS
==============
Hỗ trợ TIếng Việt, nhưng nhập liệu giọng nói Tiếng Việt không được.
NEU != POS
==============
Để làm gì khi công nghệ này lúc đó đã lỗi thời?
NEG != POS
==============
Ss quá nhiều loại, loạn cả lên
NEG != POS
==============
quá xấu, không có gì đột phá cho siêu phẩm S7, thất vọng
NEG != POS
==============
Các fan chẳng cần phải cãi nhau làm gì vì bây giờ thị trường đang dần đưa chúng về đúng giá trị của mình rồi!
NEU != POS
==============
để so sánh camera thì hơi khó bác ạ.mỗi dòng camera của mỗi hãng có những ưu điểm khác nhau.riêng như trên camera của dòng Sharp này, camera chỉ 13,1 MP nhưng hình ảnh chụp thì rất sống động, màu sắc cũng đẹp, được trang bị khẩu độ 1,9 bright eye. Thêm nữa ở camera của SH-04F lần này được trong bị thêm công nghệ Night catch 2 cho cảm nhận chụp ảnh đêm rất tuyệt. còn thì bác có thể cảm nhận thêm để xem 2 camera nó khác nhau thế nào
NEU != POS
==============
Có mình bạn thôi, chứ tui xài cái 454 3 năm rồi, có phòng đâu, mặt dù pin em nó đang chết dần ji tuổi thọ
NEU != POS
==============
Sao lại vẫn còn cái chữ Samsam thế kia, cứ phải viết ra như vậy người ta mới biết ah, trong hình có ý là được rồi thời đại này đâu dùng trong chữ có nghĩa nữa !!!
NEG != POS
==============
Lượng model cao cấp 1 năm sony tung ra băng Sam với Ip mấy năm luôn ấy :(
NEU != POS
==============
Mua dùng được vài giờ phải mang đi sạc,quá phiền nhiễu
NEG != POS
==============
Thêm 2 quả camera lồi ra như mắt ếch phía sau thì kinh hãi vô cùng!
NEG != POS
==============
nếu mua bản 16G thì bộ nhớ trong chỉ còn khoảng 11G thôi , ko có thẻ nhớ là điểm yếu , nếu chụp ảnh nhiều và game nặng nên cân nhắc , theo t nên tím shop uy tín mà mua LG G3 Mỹ cho lành .
NEG != POS
==============
Sau 1 tg lại giật lác.... Chán mấy em android giá rẻ lắm rồi
NEG != POS
==============
Cảm biến vân tay iPhone giờ chậm hơn cả Huawei, Meizu, ai định nghĩa lại ai? Vân tay chắc chắn sẽ hết thời, quá nhiều nhược điểm, cực thiếu an toàn
NEG != POS
==============
Bạn nghĩ sao lấy zenphone 2 đi so với siêu phẩm G4 vậy bạn! Note 5 hay 6s plus thì nên so với G4
NEU != POS
==============
các bác cho em hỏi có cách nào khắc phục lỗi ko đo giấc ngủ đc ko? hay của em bị lỗi rồi? nó còn ko có biểu đồ dạng cột. Hiện giờ chỉ đo mỗi bước chân. nản quá
NEU != POS
==============
Hi h van còn giữ em V3 T-Mobile , hy vọng cũng dc sang chanh ké với ng ta !
NEU != POS
==============
BB hãy học theo GG, bán hđh BB cho tất cả các hãng sx đt vsf mtb đủ điều kiện và tiêu chuẩn. Lấy phí đó phát tiển hđh BB.. Bỏ không thật là phí.
NEU != POS
==============
Giá 1,29 triệu đồng là quá đắc, vì chỉ dùng được một thời gian ngắn, Tiền nào của đó
NEG != POS
==============
Mình thì ngược lại, trước đây thích SS lắm giờ phát hiện ra màn hình SS xài mau xuống cấp nên giờ hơi ngán ngán
NEG != POS
==============
Em không biết bác thế nào như con X-T10 của em không bao giờ em mang nó ra mưa. Vì một lẽ thường tình là cao su của nó quá dở, nội mồ hôi tay dính vào thôi đã cảm thấy dinh dính tay rồi chứ đừng nói thấm nước mưa.
NEG != POS
==============
A6 vs mi band 2 con nào ngon hơn nhể
NEU != POS
==============
Nhìn như đồng hồ cũ,chẳng có tí gì tinh tế và sang trọng cả
NEG != POS
==============
không xuýt nhau đâu bác
NEU != POS
==============
Nhưng gear fit của ss chỉ tương thích với điện thoại ss -_- chứ không cũng đã mua rồi
NEU != POS
==============
Đang xài x6s, y chang em này nhưng giá mắc hơn, chả hỉu vì sao mắc hơn, ko bjk mí em này mua dây màu thay ở đâu nhỉ
NEU != POS
==============
Tùy túi tiền ban. Mình dân mua bán điện tử nên chỉ bạn Ipad 4 ngon hơn ipad 3 nhìu Ipad 4 only wifi = ipad 3 3g wifi Nếu 2 cụ ít đi tới lui khuyên mua bản ipad 4 wifi Lưu ý kinh nghiệm Xem ipad 1. Cảm ứng thay chưa (nếu thay có bụi hoặc gon màng hình ko sát) 2. Lấy số serial check lên web apple xem đúng ipad ko. Nhằm con đống ổ cứng (dính icloud) trước đó check lại ra iphone 5s 5c
NEU != POS
==============
10 người mình nhìn thấy ngoài đường thì đến 9 người cầm IP
NEU != POS
==============
Cái viền vẫn dày, cái camera vẫn lồi như ngày nào
NEG != POS
==============
Chuẩn..quá chuẩn..ifan không thích em SE..dù nghe nói mẫu iphone này là đẹp nhất của nhà Táo..nhưng do e ý giống đời cũ quá nên bị ghẻ lạnh..Tội..!
NEG != POS
==============
Dù có cải thiện nhưng Vẫn xấu và nhìn thế nào ấy nhỉ!
NEG != POS
==============
Mình đã nâng cấp và đã lãnh hậu quả: Màn hình bị rung khiến chữ và hình ảnh bị nhoè. Đã restore các kiểu vẫn không khắc phục được
NEG != POS
==============
..vấn đề mms trên i607 đến nay vẫn chưa giải quyết dc ,mọi cấu hình cài vào đều thất bại..có lẽ bạn dùng mail trên pc hoặc gửi qua phần mềm chát parlingo thôi..
NEG != POS
==============
Thêm 2 quả camera lồi ra như mắt ếch phía sau thì kinh hãi vô cùng!
NEG != POS
==============
iFan nên cảm ơn Samsung , ko có samsung thì ifan chắc chỉ dùng điện thoại cấu hình thấp , giá linh kiện rẻ mà bán giá trên trời mãi thôi .
NEG != POS
==============
để so sánh camera thì hơi khó bác ạ.mỗi dòng camera của mỗi hãng có những ưu điểm khác nhau.riêng như trên camera của dòng Sharp này, camera chỉ 13,1 MP nhưng hình ảnh chụp thì rất sống động, màu sắc cũng đẹp, được trang bị khẩu độ 1,9 bright eye. Thêm nữa ở camera của SH-04F lần này được trong bị thêm công nghệ Night catch 2 cho cảm nhận chụp ảnh đêm rất tuyệt. còn thì bác có thể cảm nhận thêm để xem 2 camera nó khác nhau thế nào
NEU != POS
==============
Xin lỗi Oppo, cho tôi cũng không lấy.
NEG != POS
==============
10 người mình nhìn thấy ngoài đường thì đến 9 người cầm IP
NEU != POS
==============
Xách tay thì thuế phí gì
NEU != POS
==============
Đọ dáng 2 chân dài GL552VW và GL752VW (riêng hình cuối: GL752 bên trái nhé)
NEU != POS
==============
Samsung là hãng bán được nhiều TV nhất thế giới. Không biết có tốt nhất không vì tôi dùng LG ..
NEU != POS
==============
có lừa cũng không tới lượt mình hưởng, hàng của người ta lưu hành nội bộ mà
NEU != POS
==============
Giá tầm 10 triệu thì mua con iPhone 6 hàng xách tay vẫn thích hơn.
NEG != POS
==============
Cái viền vẫn dày, cái camera vẫn lồi như ngày nào
NEG != POS
==============
có một từ "xấu"